[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/q/1"
  to = "/.netlify/functions/review-redirect/1"
  status = 200

[[redirects]]
  from = "/q/2"
  to = "/.netlify/functions/review-redirect/2"
  status = 200

[[redirects]]
  from = "/q/3"
  to = "/.netlify/functions/review-redirect/3"
  status = 200

[[redirects]]
  from = "/q/4"
  to = "/.netlify/functions/review-redirect/4"
  status = 200

[[redirects]]
  from = "/q/5"
  to = "/.netlify/functions/review-redirect/5"
  status = 200

[[redirects]]
  from = "/q/6"
  to = "/.netlify/functions/review-redirect/6"
  status = 200

[[redirects]]
  from = "/q/7"
  to = "/.netlify/functions/review-redirect/7"
  status = 200

[[redirects]]
  from = "/q/8"
  to = "/.netlify/functions/review-redirect/8"
  status = 200

[[redirects]]
  from = "/q/9"
  to = "/.netlify/functions/review-redirect/9"
  status = 200

[[redirects]]
  from = "/q/10"
  to = "/.netlify/functions/review-redirect/10"
  status = 200

[[redirects]]
  from = "/q/11"
  to = "/.netlify/functions/review-redirect/11"
  status = 200

[[redirects]]
  from = "/q/12"
  to = "/.netlify/functions/review-redirect/12"
  status = 200

[[redirects]]
  from = "/q/13"
  to = "/.netlify/functions/review-redirect/13"
  status = 200

[[redirects]]
  from = "/q/14"
  to = "/.netlify/functions/review-redirect/14"
  status = 200

[[redirects]]
  from = "/q/15"
  to = "/.netlify/functions/review-redirect/15"
  status = 200

[[redirects]]
  from = "/q/16"
  to = "/.netlify/functions/review-redirect/16"
  status = 200

[[redirects]]
  from = "/q/17"
  to = "/.netlify/functions/review-redirect/17"
  status = 200

[[redirects]]
  from = "/q/18"
  to = "/.netlify/functions/review-redirect/18"
  status = 200

[[redirects]]
  from = "/q/19"
  to = "/.netlify/functions/review-redirect/19"
  status = 200

[[redirects]]
  from = "/q/20"
  to = "/.netlify/functions/review-redirect/20"
  status = 200

[[redirects]]
  from = "/q/*"
  to = "/.netlify/functions/review-redirect/:splat"
  status = 200

[[headers]]
  for = "/q/*"

  [headers.values]
    Cache-Control = "no-store"
    X-Robots-Tag = "noindex, nofollow"

[[redirects]]
  from = "/product"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/product/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/en/"
  status = 301
  force = true

[[redirects]]
  from = "/en/*"
  to = "/en/index.html"
  status = 200

[[redirects]]
  from = "/tr/*"
  to = "/tr/index.html"
  status = 200

[[redirects]]
  from = "/ar/*"
  to = "/ar/index.html"
  status = 200
